config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'devise_custom/registrations' }

  mount PolicyManager::Engine => "/policies", as: 'policies'

  root 'home#index'

  get '/session/areas/:slug', to: 'session/areas#create', as: 'area'

  resources :areas, only: :show do
    member do
      get '/categories', to: 'categories#index'
      get '/categories/:category_id', to: 'categories#show'
    end

    resources :organizations, only: [:show, :new, :create, :edit, :update]
  end

  namespace :profile do
    resources :own_organizations, only: [:index]    
    resources :favorite_organizations, only: [:index]
    resources :claimed_organizations, only: [:index]
  end

  namespace :admin do
    resources :claims, only: [:index, :edit, :update]

    namespace :datatable do
      get 'table-for/:table', to: 'page#index'

      resources :organizations, only: [:index, :update]
    end
  end

  resources :organizations, only: [] do
    resources :claims, only: [:new, :create, :show, :destroy]
    resources :favorites, only: [:create, :destroy]
  end

  get '/categories/:id/organizations', to: 'organizations#index', as: 'category_organizations'

  resources :notifications, only: [:index] do
    collection do
      post :mark_as_read
    end

    post '/read', to: 'notifications#read_one'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @countries = Area.roots
  end
end

app/views/home/index.html.erb
<div class="panel panel-default">
    <div class="panel-body">
        <div class="row">
          <% @countries.each do |country| %>
            <div class="col-md-12">
                <h3><%= link_to country.name, area_path(country) %></h3>
                <hr>

                <div class="row">
                    <% country.children.each do |region| %>
                        <div class="col-md-4">
                            <h4><%= link_to region.name, area_path(region) %></h4>

                            <hr>

                            <% region.children.each do |metro| %>
                                <h5>
                                    <%= link_to metro.name, area_path(metro) %>
                                </h5>
                            <% end %>
                        </div>
                    <% end %>
                </div>
            </div>
          <% end %>
        </div>
    </div>
</div>