config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'devise_custom/registrations' }

  mount PolicyManager::Engine => "/policies", as: 'policies'

  root 'home#index'

  get '/session/areas/:slug', to: 'session/areas#create', as: 'area'

  resources :areas, only: :show do
    member do
      get '/categories', to: 'categories#index'
      get '/categories/:category_id', to: 'categories#show'
    end

    resources :organizations, only: [:show, :new, :create, :edit, :update]
  end

  namespace :profile do
    resources :own_organizations, only: [:index]    
    resources :favorite_organizations, only: [:index]
    resources :claimed_organizations, only: [:index]
  end

  namespace :admin do
    resources :claims, only: [:index, :edit, :update]

    namespace :datatable do
      get 'table-for/:table', to: 'page#index'

      resources :organizations, only: [:index, :update]
    end
  end

  resources :organizations, only: [] do
    resources :claims, only: [:new, :create, :show, :destroy]
    resources :favorites, only: [:create, :destroy]
  end

  get '/categories/:id/organizations', to: 'organizations#index', as: 'category_organizations'

  resources :notifications, only: [:index] do
    collection do
      post :mark_as_read
    end

    post '/read', to: 'notifications#read_one'
  end
end

app/models/organization.rb
class Organization < ApplicationRecord
  include AlgoliaSearch

  belongs_to :area
  belongs_to :category
  belongs_to :submitter, class_name: "User", foreign_key: "user_id", optional: true

  has_many :favorites, as: :favoritable
  has_many :favoriters, through: :favorites, source: :user
  
  has_many :claims
  has_many :claimants, through: :claims, class_name: "User", source: :user

  has_many :approved_claims, -> { where approved: true }, class_name: "Claim"
  has_many :owners, through: :approved_claims, source: :user

  scope :in_area, -> (area) { where(area_id: area.descendant_ids.push(area.id)) }
  scope :from_category, -> (category) { where(category_id: category.descendant_ids.push(category.id)) }

  scope :live, -> { where(live: true) }
  scope :not_live, -> { where.not(live: true) }

  algoliasearch per_environment: true, unless: :hide_from_algolia?, disable_indexing: Rails.env.test? do
    attribute :id, :title, :mission

    attribute :created_at do
      created_at.strftime("%b %d, %Y")
    end

    attribute :updated_at do
      updated_at.strftime("%b %d, %Y")
    end

    attribute :area do
      { 
        id: area.id, 
        name: area.name, 
        slug: area.slug,
        parent_id: area.parent_id
      }
    end

    attribute :category do
      {
        id: category.id,
        name: category.name,
        slug: category.slug,
        parent_id: category.parent_id
      }
    end
  end

  def hide_from_algolia?
    !self.live?
  end

  def post_read_path_for(user)
    @claim = Claim.where(organization: self, user: user).first

    Rails.application.routes.url_helpers.edit_admin_claim_path(@claim)
  end

  def area_name=(name)
    area = Area.find_by(name: name)

    area = Area.create(name: name) unless !!area
    
    self.area_id = area.id
  end

  def category_name=(name)
    category = Category.find_by(name: name)

    category = Category.create(name: name) unless !!category

    self.category_id = category.id
  end
end

app/controllers/admin/datatable/organizations_controller.rb
class Admin::Datatable::OrganizationsController < Admin::Datatable::DatatableController
  def selectable_columns
    displayable_columns
  end

  def displayable_columns
    ['id', 'title', 'mission', 'areas.name as area_name', 'categories.name as category_name', 'live']
  end

  def updatable_columns
    super
  end

  def update
    @org = Organization.find(params[:id])

    if @org.update(org_params)
      render json: {success: true, org: @org}
    else
      head :error
    end
  end

  private

    def builder
      ::Organization.joins(:area, :category)
    end

    def org_params
      params.permit(:title, :mission, :area_name, :category_name, :live)
    end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
    @category = Category.find_by(slug: params[:id])

    @organizations = Organization.in_area(@area).from_category(@category)
  end

  def new
    @organization = Organization.new
  end

  def show
    @organization = Organization.find_by(id: params[:id])

    if !!current_user
      @favorite = Favorite.where(favoritable: @organization, user: current_user).first
      @claim = Claim.where(organization: @organization).first
    end

    respond_to do |f|
      f.html {  }
      f.json { render jsonapi: @organization }
    end
  end

  def create
    @organization = Organization.new(org_params)

    if current_user_has_consented_to_all?
      @organization.submitter = current_user
    end

    if @organization.save
      flash[:success] = "Organization successfully created"
      redirect_to area_organization_path(@area, @organization)
    else
      flash.now[:error] = "Something went wrong."
      render :new
    end
  end

  def edit
    @organization = Organization.find_by(id: params[:id])
  end

  def update
    @organization = Organization.find_by(id: params[:id])

    if @organization.update(org_params)
      flash[:success] = "Organization successfully updated"
      redirect_to area_organization_path(@area, @organization)
    else
      flash.now[:error] = "Something went wrong."
      render :edit
    end
  end

  private

    def org_params
      params.require(:organization).permit(:title, :area_id, :category_id, :mission)
    end
end

app/views/organizations/_form.html.erb
<div class="panel-body">
  <%= form_for [@area, @organization], html: { class: "form-horizontal", role: "form" } do |f| %>
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :title %>
      </div>

      <div class="col-md-8">
        <%= f.text_field :title, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :area_id %>
      </div>

      <div class="col-md-8">
        <%= f.collection_select :area_id, Area.all, :id, :name, {selected: @organization.area_id}, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :category_id %>
      </div>

      <div class="col-md-8">
        <%= f.collection_select :category_id, Category.all, :id, :name, {selected: @organization.category_id}, class: 'form-control' %>
      </div>
    </div>    

    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :mission %>
      </div>
      
      <div class="col-md-8">
        <%= f.text_area :mission, rows: 10, class: 'form-control', placeholder: 'What does this organization do?' %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-md-10 col-md-offset-2">
        <%= f.submit "Submit", class: "btn btn-primary btn-lg btn-xlarge" %>
      </div>
    </div>

  <% end %>
</div>
<!--   <form action="{{ route('listings.store', [$area]) }}" method="POST">

    @include('listings.partials.forms._areas')

    @include('listings.partials.forms._categories')                 

    <div class="form-group{{ $errors->has('title') ? ' has-error' : '' }}">
      <label for="title" class="control-label">Title</label>

      <input type="text" name="title" id="title" class="form-control">

      @if($errors->has('title'))
        <span class="help-block">
          {{ $errors->first('title') }}
        </span>
      @endif
    </div>

    <div class="form-group{{ $errors->has('body') ? ' has-error' : '' }}">
      <label for="body" class="control-label">Body</label>

      <textarea name="body" id="body" class="form-control" rows="5"></textarea>

      @if($errors->has('body'))
        <span class="help-block">
          {{ $errors->first('body') }}
        </span>
      @endif                
    </div>                         

    <div class="form-group">
      <button class="btn btn-default" type="submit">Submit</button>
    </div>
  </form> -->

app/views/organizations/edit.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">

          <div class="panel-heading">Edit <%= @organization.title %>'s Listing</div>

          <%= render 'form' %>
        </div>
    </div>
</div>

app/views/organizations/index.html.erb
<div class="row">
  <%= render 'partials/search' %>

  <h4><%= @category.parent.name %> &nbsp; > &nbsp; <%= @category.name %></h4>

  <% @organizations.each do |org| %>
    <div class="media">
      <div class="media-body">
        <h5>
          <strong>
            <%= link_to org.title, area_organization_path(current_area, org) %>
          </strong>

          <% if @area.children.count > 0 %>
            in <%= org.area.name %>
          <% end %>
        </h5>

        <ul class="list-inline">
          <li><time>submitted <%= time_ago_in_words org.created_at %> ago</time></li>
          <% if !!org.submitter %>
            <li>by <%= org.submitter.email %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>
</div>

app/views/organizations/new.html.erb
<div class="row">
    <div class="col-md-8 col-md-offset-2">
        <div class="panel panel-default">

          <div class="panel-heading">Create Organization Listing</div>

          <%= render 'form' %>
        </div>
    </div>
</div>

app/views/organizations/show.html.erb
<div class="row">
  <div class="col-md-3">
    <div class="panel panel-default">
      <div class="panel-body">
        <ul class="nav nav-pills nav-stacked">
          <!-- authenticated user behavior -->
          <% if !!current_user %>
            <% unless current_user.favorite_organizations.include?(@organization) %>
              <li role="presentation">
                <%= link_to "Add to favorites", organization_favorites_path(@organization), method: :post %>
              </li>
            <% else %>
              <li role="presentation">
                <%= link_to "Remove from favorites", organization_favorite_path(@organization, @favorite), method: :delete %>
              </li>
            <% end %>

            <% unless current_user.claimed_organizations.include?(@organization) %>
              <li role="presentation">
                <%= link_to "Apply to claim this organization", new_organization_claim_path(@organization), class: "btn danger" %>
              </li>
            <% else %>
              <li role="presentation">
                <%= link_to "Withdraw claim", organization_claim_path(@organization, @claim), class: "btn danger", method: :delete %>
              </li>
            <% end %>

          <!-- guest user behavior -->
          <% else %>
                Please <%= link_to "log in", new_user_session_path %> or <%= link_to "register", new_user_registration_path %> to save or claim this organization.         
          <% end %>
        </ul>
      </div>
    </div>
  </div>

  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4><%= @organization.title %> <span class="text-muted">in <%= @organization.area.name %> -> <%= @organization.category.name %></span></h4>
      </div>

      <div class="panel-body">
        <%= @organization.mission %>

        <hr>

        <% if @organization.submitter %>
          <p>
            <small>
              Submitted by <%= @organization.submitter.email %>
            </small>
          </p>
        <% end %>
        
        <p><small>Viewed X times</small></p>
      </div>
    </div>    
  </div>
</div>