config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'devise_custom/registrations' }

  mount PolicyManager::Engine => "/policies", as: 'policies'

  root 'home#index'

  get '/session/areas/:slug', to: 'session/areas#create', as: 'area'

  resources :areas, only: :show do
    member do
      get '/categories', to: 'categories#index'
      get '/categories/:category_id', to: 'categories#show'
    end

    resources :organizations, only: [:show, :new, :create, :edit, :update]
  end

  namespace :profile do
    resources :own_organizations, only: [:index]    
    resources :favorite_organizations, only: [:index]
    resources :claimed_organizations, only: [:index]
  end

  namespace :admin do
    resources :claims, only: [:index, :edit, :update]

    namespace :datatable do
      get 'table-for/:table', to: 'page#index'

      resources :organizations, only: [:index, :update]
    end
  end

  resources :organizations, only: [] do
    resources :claims, only: [:new, :create, :show, :destroy]
    resources :favorites, only: [:create, :destroy]
  end

  get '/categories/:id/organizations', to: 'organizations#index', as: 'category_organizations'

  resources :notifications, only: [:index] do
    collection do
      post :mark_as_read
    end

    post '/read', to: 'notifications#read_one'
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_ancestry

  include Slugable

  after_initialize :set_prefixed_slug

  validates_presence_of :name, :slug
  validates_uniqueness_of :slug

  has_many :organizations
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @area = Area.find_by(slug: params[:id])
    @categories = Category.roots
  end
end

app/views/categories/index.html.erb
<div class="row">
  <%= render 'partials/search' %>

  <% @categories.each do |category| %>
    <div class="col-md-4">
      <h5><%= category.name %></h5>
      <hr>

      <% category.children.each do |inter| %>
        <h5><%= link_to inter.name, category_organizations_path(inter), class: 'bold-link' %> <!-- listings count --></h5>

        <div class="row">
          <% inter.children.each do |sub| %>
            <div class="col-md-4">
              <h6><%= link_to sub.name, category_organizations_path(sub), class: 'small-link' %> <!-- listings count --></h6>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  <% end %>
</div>