config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'devise_custom/registrations' }

  mount PolicyManager::Engine => "/policies", as: 'policies'

  root 'home#index'

  get '/session/areas/:slug', to: 'session/areas#create', as: 'area'

  resources :areas, only: :show do
    member do
      get '/categories', to: 'categories#index'
      get '/categories/:category_id', to: 'categories#show'
    end

    resources :organizations, only: [:show, :new, :create, :edit, :update]
  end

  namespace :profile do
    resources :own_organizations, only: [:index]    
    resources :favorite_organizations, only: [:index]
    resources :claimed_organizations, only: [:index]
  end

  namespace :admin do
    resources :claims, only: [:index, :edit, :update]

    namespace :datatable do
      get 'table-for/:table', to: 'page#index'

      resources :organizations, only: [:index, :update]
    end
  end

  resources :organizations, only: [] do
    resources :claims, only: [:new, :create, :show, :destroy]
    resources :favorites, only: [:create, :destroy]
  end

  get '/categories/:id/organizations', to: 'organizations#index', as: 'category_organizations'

  resources :notifications, only: [:index] do
    collection do
      post :mark_as_read
    end

    post '/read', to: 'notifications#read_one'
  end
end

app/views/layouts/partials/_consent_forms.html.erb
<% if current_user %>

  <% if show_cookie_form?(current_user) %>
    <hr>
    <div class="panel panel-default">
      <h4>Cookie policy</h4>
      <p>
        <%= @cookie %>
      </p>

      <form action="/policies/user_terms/cookie/accept" accept-charset="UTF-8" method="post"><input name"=utf8" type="hidden" value="✓"><input type="hidden" name="_method" value="put"><input type="hidden" name="authenticity_token" value="<%=  %>">
              <input type="submit" name="commit" value="Accept" class="btn btn-success" data-disable-with="Accept">
              <a class="btn btn-secondary" href="/policies/user_terms/pending">No not now</a>
      </form>
    </div>
  <% end %>

  <% if show_age_form?(current_user) %>
    <hr>
    <div class="panel panel-default">
      <h4>Age policy</h4>
      <p>      
        <%= @age %>
      </p>

      <form action="/policies/user_terms/age/accept" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="_method" value="put"><input type="hidden" name="authenticity_token" value="<%= %>">
              <input type="submit" name="commit" value="Accept" class="btn btn-success" data-disable-with="Accept">
              <a class="btn btn-secondary" href="/policies/user_terms/pending">No not now</a>
      </form>      
    </div>
  <% end %>

  <% if show_privacy_form?(current_user) %>
    <hr>
    <div class="panel panel-default">
      <h4>Privacy policy</h4>
      <p>      
        <%= @privacy_terms %>
      </p>

      <form action="/policies/user_terms/privacy_terms/accept" accept-charset="UTF-8" method="post"><input name="utf8" type="hidden" value="✓"><input type="hidden" name="_method" value="put"><input type="hidden" name="authenticity_token" value="<%= %>">
              <input type="submit" name="commit" value="Accept" class="btn btn-success" data-disable-with="Accept">
              <a class="btn btn-secondary" href="/policies/user_terms/pending">No not now</a>
      </form>      
    </div>
  <% end %>
<% end %>

app/views/layouts/partials/_flash.html.erb
<div class="row">
  <div class="col-md-10 col-md-offset-1">
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <% if !!current_user && current_user.pending_policies.length > 0 %>
      <div class="alert alert-danger">
          <h2>IMPORTANT: You have pending privacy agreements</h2>
          <h4><%= link_to "Click Here", policies.pending_user_terms_path %> to view them.</h4>
      </div>
        
    <% end %>

    <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
      
    <% end %>
  </div>
</div>

app/views/layouts/partials/_head.html.erb
<title>AdvocacyListings</title>
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/partials/_nav.html.erb
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse" aria-expanded="false">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <%= link_to !!current_area ? current_area.name : 'Home', root_path, class: 'navbar-brand' %>
        </div>

        <div class="collapse navbar-collapse" id="app-navbar-collapse">
            <!-- Left Side Of Navbar -->
            <ul class="nav navbar-nav">
                <li>
                    <%= link_to 'Categories', categories_area_path(current_area) if !!current_area %>
                </li>
            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="nav navbar-nav navbar-right">
                <!-- Authentication Links -->
                <!-- logged in links -->
                <% if user_signed_in? %>
                    <li>
                        <!-- <a href="{{ route('listings.favorites.index', [$area]) }}">Favorites</a> -->
                    </li>
                    <li>
                        <!-- <a href="{{ route('listings.viewed.index', [$area]) }}">Recently Viewed</a> -->
                    </li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                            Organizations <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu">
                            <li>
                                <%= link_to "New Organization", new_area_organization_path(current_area || 'united-states') %>
                            </li>

                            <li>
                               <%= link_to "Your Owned Orgs", profile_own_organizations_path %>
                            </li>

                            <li>
                                <%= link_to "Pending Claims", profile_claimed_organizations_path %>
                            </li>

                            <li>
                                <%= link_to "Favorite Organizations", profile_favorite_organizations_path %>
                            </li>                            
                        </ul>
                    </li>

                    <app-notifications></app-notifications>

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false" aria-haspopup="true" v-pre>
                            <%= current_user.email %> <span class="caret"></span>
                        </a>

                        <ul class="dropdown-menu">
                            <li>
                                <%= link_to "Log out", destroy_user_session_path, method: :delete %>
                            </li>
                        </ul>
                    </li>
                <% else %>
                <!-- guest links @guest -->
                    <li>
                        <%= link_to "Log In", new_user_session_path %>
                    </li>
                    <li>
                        <%= link_to "Register", new_user_registration_path %>
                    </li>
                <% end %>
            </ul>
        </div>
    </div>
</nav>